stages:
  process_data:
    cmd: python3 src/code/make_dataset.py src/data/raw/nyu_depth_v2_labeled.mat src/data/raw/splits.mat
      src/data/processed
    deps:
    - src/code/make_dataset.py
    - src/data/raw/nyu_depth_v2_labeled.mat
    - src/data/raw/splits.mat
    outs:
    - src/data/processed/
  train:
    cmd: python3 src/code/training.py src/data/processed src/models
    deps:
    - src/code/training.py
    - src/data/processed/
    outs:
    - src/models/
